### ISSUE TITLE
Replace img tag with a tag

### ISSUE THREAD

**Issue by shm04** [JuanDiegoGuerra/Portfolio-Setup-and-Mobile-first#10]
https://github.com/JuanDiegoGuerra/Portfolio-Setup-and-Mobile-first/blob/67a7a245485899fd7fc778e179199045439e93ae/index.html#L280-L283

It would be better to replace the img tag with a tag so that you can include a link to all the social media icons.

**Comment by JuanDiegoGuerra** [comment]
I will work on that! Thanks!
