### ISSUE TITLE
Peer to peer code review (morning sessions)

### ISSUE THREAD

**Issue by tomasesquivelgc** [JuanDiegoGuerra/Portfolio-Setup-and-Mobile-first#13]
Great job with the navbar! One thing you could change to make your code even cleaner is to change the "addEventListener" to "onclick".
This is so that the click is only attached to one function. It can save you a lot of trouble down the line.

**Comment by JuanDiegoGuerra** [comment]
Thank u for your feedback! I'll try to improve that asap 😁.
