### ISSUE TITLE
Peer to peer review issues and bug

### ISSUE THREAD

**Issue by lordksix** [JuanDiegoGuerra/Portfolio-Setup-and-Mobile-first#6]
- Strong tags should not be used for styling, but to put semantic emphasis.
- There are repeated elements in the HTML that is used for styling. CSS should be used for styling.
- There is a bug in responsiveness when resizing and on the form description

**Comment by JuanDiegoGuerra** [comment]
Thanks for the feedback! I will try to fix everything you pointed 🙌🏼!
